server:
  port: 80
  servlet:
    session:
      timeout: 1m # session会话超时时间，默认情况 下是30分钟（m）,不能小于1分钟
      cookie:
        name: JSESSIONID # 指定浏览器Cookie中关于SessionID保存的那个名称

spring:
  session:
    store-type: redis # session存储方式采用 redis
  redis: # 如果是本地redis可不配置
    port: 6379
    host: 192.168.247.100

  thymeleaf:
    cache: true #关闭thymeleaf缓存
  # 数据源配置
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.247.100:3306/manba-security?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
    #mysql8版本以上驱动包指定新的驱动类
    driver-class-name: com.mysql.cj.jdbc.Driver

manba:
  security:
    authentication:
      loginPage: /login/page
      loginProcessingUrl: /login/form
      usernameParameter: name
      passwordParameter: pwd
      staticPaths:
      - /dist/**
      - /modules/**
      - /plugins/**
      loginType: REDIRECT # 认证之后 响应的类型：JSON/REDIRECT
      imageCodeUrl:  /code/image # 获取图形验证码 url
      mobileCodeUrl: /code/mobile # 发送手机验证码 url
      mobilePage: /mobile/page # 前往手机登录页面地址
      tokenValiditySeconds: 604800 # 记住我有效时长，单位秒， 注意不要用乘法*，会被认为字符串

